FROM openjdk:8-jre-slim

MAINTAINER seele

RUN apt update && apt install -y curl && mkdir -p /home/seele
WORKDIR /home/seele
COPY ./jar /home/seele

ENTRYPOINT ["java","-jar","seele-base-service.jar"]